# Generated by Django 4.0.5 on 2022-08-03 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lovencakes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='prod', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
